spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fisher_map
    username: postgres
    password: dapsYzsv1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      max-lifetime: 1200000
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql=true:

  liquibase.change-log: classpath:/db/changelog/changelog_master.xml
logging:
  level:
    liquibase: INFO


aws:
  access:
    key:
      id: AKIAZGO7MZIDIMSDAOUE
      secret: 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
  region: us-east-2
  s3:
    audio:
      bucket: spirit-bucket
